Repository rachelsoae/humor-me-ui, pull requests merged in 2023-07, with the labels that each got.

#24 Feat/component building and styling
  public/index.html
  public/logo192.png
  public/logo512.png
  src/App/App.css
  src/App/App.js
  src/Card/Card.css
  src/Card/Card.js
  src/Favorites/Favorites.css
  src/Favorites/Favorites.js
  src/Form/Form.css
  src/Form/Form.js
  src/Home/Home.css
  src/Home/Home.js
  src/Nav/Nav.js
Labels: new feature

#36 Feat/functionality
  public/index.html
  src/App/App.css
  src/App/App.js
  src/Card/Card.css
  src/Card/Card.js
  src/Favorites/Favorites.css
  src/Favorites/Favorites.js
  src/Form/Form.css
  src/Form/Form.js
  src/Home/Home.css
  src/Home/Home.js
  src/Nav/Nav.css
  src/Nav/Nav.js
  src/Poster/Poster.css
  src/Poster/Poster.js
  src/apiCalls.js
  src/index.css
  src/mockData.js
Labels: new feature

#43 Refactor/api calls
  src/App/App.css
  src/App/App.js
  src/Card/Card.js
  src/Error/Error.css
  src/Error/Error.js
  src/Favorites/Favorites.css
  src/Favorites/Favorites.js
  src/Form/Form.js
  src/Home/Home.css
  src/Home/Home.js
  src/Nav/Nav.css
  src/Nav/Nav.js
  src/Poster/Poster.css
  src/Poster/Poster.js
  src/apiCalls.js
  src/index.css
  src/mockData.js
Labels: new feature, High Priority

#47 Feat/cypress testing
  cypress.config.js
  cypress/e2e/create.cy.js
  cypress/e2e/favorites.cy.js
  cypress/e2e/home.cy.js
  cypress/e2e/random.cy.js
  cypress/fixtures/example.json
  cypress/fixtures/images.json
  cypress/fixtures/newPoster.json
  cypress/fixtures/null.json
  cypress/fixtures/posters.json
  cypress/fixtures/quotes.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  src/App/App.js
  src/Form/Form.js
Labels: bug, refactor, High Priority

#54 Feat/prop types
  package-lock.json
  package.json
  src/Card/Card.js
  src/Favorites/Favorites.js
  src/Form/Form.js
  src/Home/Home.js
  src/Poster/Poster.js
Labels: new feature

#57 Refactor/update routes random generation
  cypress/e2e/random.cy.js
  src/App/App.js
  src/Form/Form.js
  src/Poster/Poster.js
Labels: bug

#61 Fix/cypress commands
  cypress/e2e/create.cy.js
  cypress/e2e/favorites.cy.js
  cypress/e2e/home.cy.js
  cypress/e2e/random.cy.js
  cypress/support/commands.js
  src/App/App.js
Labels: bug, refactor
